- include: "common.yml"
- include: "mysql.yml"
- include: "pgsql.yml"
- include: "memcached.yml"
- include: "redis.yml"
- include: "elasticsearch.yml"
- include: "python.yml"
- include: "robotframework.yml"
- include: "nodejs.yml"
- include: "disable_updates.yml"
